name: GameModeEZ
main: GameModeEZ\Main
author: HuaYoyu
website: "https://github.com/HuaYoyuDoge/GameModeEZ"
description: Ez ways to change u gamemode
version: INDEV
api: 2.0.0
commands:
    gmhelp:
        usage: /gmhelp
        description: Shows plugin help
    gms:
        usage: /gms
        description: Changes gamemode to Survival 
    gmc:
        usage: /gmc
        description: Changes gamemode to Creative
    gma:
        usage: /gma
        description: Changes gamemode to Adventure
    gmsp:
        usage: /gmsp
        description: Changes gamemode to Spectator
permissions:
    gmhelp.gms:
        default: op
        description: Allows use of /gms
    gmhelp.gmc:
        default: op
        description: Allows use of /gmc
    gmhelp.gma:
        default: op
        description: Allows use of /gma
    gmhelp.gmsp:
        default: op
        description: Allows use of /gmsp
