name: GameModeEZ
main: GameModeEZ\Main
author: HuaYoyu
description: Ez ways to change u gamemode
version: 0.1beta
api: 2.0.0
commands:
    gmhelp:
        usage: /gmhelp
        description: Shows plugin help
